# -*- coding: utf-8 -*-
"""Garbage_classification_updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W0hvY6UUOozMlPngQbRwnI13GWA54yY_

# **Dataset context**

The Garbage Classification dataset was created to support the development of machine learning models for automated waste sorting and recycling systems. It consists of labeled images of various types of garbage, such as cardboard, glass, metal, paper, plastic and general trash. The goal is to train models to recognize and classify these waste types based on visual characteristics.

This dataset is particularly useful for computer vision applications in environmental sustainability, where automatic identification of recyclable materials can aid in improving waste management efficiency, reducing human error and supporting smart bin technologies. Its real-world variability—such as different lighting, angles, and backgrounds—makes it suitable for building robust image classification systems.

# **Dataset content**

* **Total Classes**: 6 categories of garbage:

 - 1. cardboard

 - 2. glass

 - 3. metal

 - 4. paper

 - 5. plastic

 - 6. trash

* **File Format**: Images are stored as .jpg files. Typical image dimensions vary (e.g., ~384x512 pixels), but can be resized for modeling.

* **Labeling**: Each folder name serves as the class label for the images it contains.

* **Number of Images**: ~2,500–2,600 total images (approx. 400–500 per class).

* **Image Variety**: Photos include various object shapes, sizes, and backgrounds to mimic real-world conditions. Some images show used/dirty items, others are clean, making it suitable for generalization.

*(source: https://www.kaggle.com/datasets/asdasdasasdas/garbage-classification/data)*

# **Imports**
"""

# Standard Library Imports
import glob
import os
import zipfile
from typing import Dict, Union, List
from google.colab import files

# Data Manipulation & Visualization
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Utility & Interface
from IPython.display import display
import ipywidgets as widgets

# Image Processing
from PIL import Image
from skimage import io, transform

# Machine Learning & Model Evaluation
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

# Deep Learning – Keras
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense, Flatten, Dropout, Conv2D, MaxPooling2D, BatchNormalization, Activation, LayerNormalization
from tensorflow.keras.metrics import Precision, Recall, AUC, TopKCategoricalAccuracy
from tensorflow.keras import regularizers

# Deep Learning – TensorFlow (Keras backend)
import tensorflow as tf
from tensorflow.keras import regularizers
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras import Model, Input

# Deep Learning – PyTorch
import torch

"""# **Functions**"""

def handle_upload(change: dict) -> None:
    """
    Handles the upload event for Kaggle JSON credential file.
    """
    if uploader.value:
        for fname, file in uploader.value.items():
            # Save the file temporarily
            with open("kaggle.json", "wb") as f:
                f.write(file["content"])
                print("kaggle.json saved locally.")

        # Create the .kaggle directory if it doesn't exist
        kaggle_dir = os.path.expanduser("~/.kaggle")
        os.makedirs(kaggle_dir, exist_ok=True)
        # Move the file to ~/.kaggle
        os.replace("kaggle.json", os.path.join(kaggle_dir, "kaggle.json"))
        print("kaggle.json moved to ~/.kaggle")

def load_and_inspect_dataset(set_path: str, label_map: Dict[int, str])-> pd.DataFrame:
    """
    Loads training data from a CSV file, inspects its structure, maps numeric labels to class names,
    and prints summary information.
    """
    # Read the train data
    df = pd.read_csv(set_path, header=None, names=['picture', 'label'], delimiter=" ")

    # Display top 5 rows
    print("First 5 rows of the dataset:")
    print(df.head())

    # Check for missing values
    print("\n\nMissing values in each column:")
    print(df.isnull().sum())

    # Map label integers to class names
    df['label_name'] = df['label'].map(label_map)

    # Display dataset size
    print(f"\n\nTotal number of training examples: {len(df)}")

    # Show class distribution
    print("\n\nLabel distribution:")
    print(df['label'].value_counts())

    # Show info about DataFrame
    print("\n\nDataFrame info:")
    df.info()

    return df

def plot_label_distribution(df: pd.DataFrame) -> None:
    """
    Generates and displays a count plot for label distribution in the given DataFrame.
    """
    sns.set(style="whitegrid")
    plt.figure(figsize=(8, 5))
    sns.countplot(data=df, x='label_name', order=df['label_name'].value_counts().index)
    plt.xlabel('Label')
    plt.ylabel('Count')
    plt.title('Label Distribution in train_df')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

def display_sample_images(df: pd.DataFrame, data_dir: Union[str, os.PathLike]) -> None:
    """
    Displays one sample image per class from the training dataset with class labels.
    """
    classes = df['label_name'].unique()
    for label in classes:
        # Get the first sample image for the label
        sample = df[df['label_name'] == label].iloc[0]
        img_path = os.path.join(data_dir, sample['label_name'], str(sample['picture']))

        try:
            img = Image.open(img_path)
            plt.figure()
            plt.imshow(img)
            plt.title(f"Label: {label}")
            plt.axis('off')
            plt.show()
        except FileNotFoundError:
            print(f"Image file not found: {img_path}")

def evaluate_model(trained_model: Sequential) -> None:
    """
    Visualizes the training and validation accuracy and loss over epochs from a trained Keras model.
    """
    accuracy = trained_model.history.history['accuracy']
    val_accuracy = trained_model.history.history['val_accuracy']
    loss = trained_model.history.history['loss']
    val_loss = trained_model.history.history['val_loss']
    epochs = range(len(accuracy))

    plt.plot(epochs, accuracy, 'bo', label='Training accuracy')
    plt.plot(epochs, val_accuracy, 'b', label='Validation accuracy')
    plt.title('Training and validation accuracy')
    plt.legend()

    plt.figure()
    plt.plot(epochs, loss, 'bo', label='Training loss')
    plt.plot(epochs, val_loss, 'b', label='Validation loss')
    plt.title('Training and validation loss')
    plt.legend()

    plt.show()

def plot_confusion_matrix(model: Sequential, test_iterator) -> None:
    """
    Generates and displays a visually enhanced confusion matrix for a given model's predictions.
    """
    y_true = test_iterator.classes
    y_pred_probs = model.predict(test_iterator, verbose=1)
    y_pred = np.argmax(y_pred_probs, axis=1)
    labels = [label for label, index in sorted(test_iterator.class_indices.items(), key=lambda x: x[1])]

    cm = confusion_matrix(y_true, y_pred)

    fig, ax = plt.subplots(figsize=(12, 8))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
    disp.plot(ax=ax, cmap='Blues', xticks_rotation=45, colorbar=False)

    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.grid(False)

    plt.title('Confusion Matrix')
    plt.tight_layout()
    plt.show()

def generate_confusion_matrix_and_classification_report(model: Sequential, test_iterator) -> None:
    """
    Computes and returns the confusion matrix for a given model and test data iterator.
    """
    # Ensure consistent results by resetting the iterator
    test_iterator.reset()

    # Ground truth labels
    y_true = test_iterator.classes

    # Model predictions
    y_pred_probs = model.predict(test_iterator, verbose=1)
    y_pred = np.argmax(y_pred_probs, axis=1)

    # Display label mapping
    sorted_labels = [label for label, index in sorted(test_iterator.class_indices.items(), key=lambda x: x[1])]
    print("Label order:", sorted_labels)

    # Print confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    print("Confusion Matrix:\n", cm)

def predict_image(model, img_path, class_labels) -> str:
    """
    Predicts the class of an input image using a trained MobileNetV2 model.
    """

    # Load and preprocess the image
    img = image.load_img(img_path, target_size=(128, 128))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)

    # Predict
    predictions = model.predict(img_array)
    predicted_index = np.argmax(predictions, axis=1)[0]
    predicted_label = class_labels[predicted_index]

    # Show image and prediction
    plt.imshow(img)
    plt.axis('off')
    plt.title(f"Predicted: {predicted_label}")
    plt.show()

    return predicted_label

def count_params_manual(weights: List[tf.Variable]) -> int:
    """
    Manually count the number of parameters in a list of TensorFlow weights.
    """
    return int(np.sum([np.prod(w.shape) for w in weights]))

# Callback to monitor gradients per epoch
class GradientMonitor(tf.keras.callbacks.Callback):
    def __init__(self):
        super().__init__()
        self.avg_gradients = []

    def on_epoch_end(self, epoch, logs=None):
      """
      Called at the end of each training epoch.
      Computes the gradient norms of the model's trainable variables for the first batch
      of the training data and prints the average gradient norm.

      """
      grads = []
      for x, y in train_iterator:
          with tf.GradientTape() as tape:
              y_pred = self.model(x, training=True)
              loss = tf.keras.losses.categorical_crossentropy(y, y_pred)
          batch_grads = tape.gradient(loss, self.model.trainable_variables)
          batch_norms = [tf.norm(g).numpy() for g in batch_grads if g is not None]
          grads.extend(batch_norms)
          break  # only first batch
      avg_grad = np.mean(grads)
      self.avg_gradients.append(avg_grad)
      print(f"Epoch {epoch+1} average gradient norm: {avg_grad:.4f}")

def save_model_performance(name: str,
                           test_acc: List[float],
                           test_loss: List[float],
                           test_top_acc: List[float],
                           avg_grad_norms: float,
                           train_params: List[int],
                           non_train_params: List[int],
                           model: Model,
                           test_eval: List[float],
                           grad_monitor: GradientMonitor = None) -> None:
    """
    Appends performance metrics and parameter counts of a model to tracking lists.
    """
    model_name.append(name)
    test_acc.append(test_eval[1])
    test_loss.append(test_eval[0])
    test_top_acc.append(test_eval[4])
    train_params.append(count_params_manual(model.trainable_weights))
    non_train_params.append(count_params_manual(model.non_trainable_weights))

    avg_grad = np.mean(grad_monitor.avg_gradients)
    avg_grad_norms = avg_grad

"""# **Data preparation and downloading**"""

# Upload kaggle.json
uploader = widgets.FileUpload(accept='.json', multiple=False)
display(uploader)

# Attach the handler to the uploader
uploader.observe(handle_upload, names='value')

# Download dataset
!kaggle datasets download -d asdasdasasdas/garbage-classification

# Unzip the data
with zipfile.ZipFile("garbage-classification.zip", 'r') as zip_ref:
    zip_ref.extractall("garbage_dataset")

# The data consists of 5 text files
for root, dirs, files in os.walk("garbage_dataset"):
    print(f"Directory: {root}")
    print(f"Files: {files[:5]}")
    break

"""# EDA"""

# There are 6 labels of garbage: cardboard, glass, metal, paper, plastic and trash
data_dir  = './garbage_dataset/Garbage classification/Garbage classification'

classes = os.listdir(data_dir)
print(classes)

# Define train, test and val sets paths
train_dir = './garbage_dataset/one-indexed-files-notrash_train.txt'
test_dir = './garbage_dataset/one-indexed-files-notrash_test.txt'
val_dir = './garbage_dataset/one-indexed-files-notrash_val.txt'

# Map the labels of data to put them on the plots
label_map = {1: 'glass', 2: 'paper', 3: 'cardboard', 4: 'plastic', 5: 'metal', 6: 'trash'}

"""## **Train set**"""

# There are no missing values
# Total number of examples for train set is 1768
train_df = load_and_inspect_dataset(train_dir, label_map)

# There are the most glass examples (403) and the least trash examples (91)
plot_label_distribution(train_df)

# Display sample images per class for train set
display_sample_images(train_df, data_dir)

"""## **Test set**"""

# There are no missing values
# Total number of examples for train set is 431
test_df = load_and_inspect_dataset(test_dir, label_map)

# There are the most glass examples (108) and the least trash examples (29)
plot_label_distribution(test_df)

# Display sample images per class for test set
display_sample_images(test_df, data_dir)

"""## **Validation set**"""

# There are no missing values
# Total number of examples for train set is 328
val_df = load_and_inspect_dataset(val_dir, label_map)

# There are the most glass examples (83) and the least trash examples (17)
plot_label_distribution(val_df)

# Display sample images per class for test set
display_sample_images(val_df, data_dir)

"""# Generators and iterators for each set"""

# Define relative paths for all sets
train_df['rel_path'] = train_df['label_name']+'/'+train_df['picture']
test_df['rel_path'] = test_df['label_name']+'/'+test_df['picture']
val_df['rel_path'] = val_df['label_name']+'/'+val_df['picture']

# Generators
train_generator = ImageDataGenerator(
    rescale = 1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)
val_generator = ImageDataGenerator(rescale = 1./255)
test_generator = ImageDataGenerator(rescale = 1./255)

# Iterators
train_iterator = train_generator.flow_from_dataframe(train_df,
                                                     directory = data_dir,
                                                    x_col='rel_path',
                                                    y_col='label_name',
                                                    target_size=(128, 128),
                                                    batch_size=32,
                                                    class_mode='categorical',
                                                    shuffle=True)

val_iterator = val_generator.flow_from_dataframe(val_df,
                                                 directory =  data_dir,
                                                    x_col='rel_path',
                                                    y_col='label_name',
                                                    target_size=(128, 128),
                                                    batch_size=32,
                                                    class_mode='categorical',
                                                    shuffle=True)

test_iterator = test_generator.flow_from_dataframe(test_df,
                                                    directory = data_dir,
                                                    x_col='rel_path',
                                                    y_col='label_name',
                                                    target_size=(128, 128),
                                                    batch_size=32,
                                                    class_mode='categorical',
                                                    shuffle=True)

"""# Models"""

# Gather results for each model
model_name = []
test_acc = []
test_loss = []
test_top_acc = []
train_params = []
non_train_params = []
avg_grad_norms = []

"""## Model 1"""

# Architecture (CNN with MaxPooling)
model_I = Sequential()

model_I.add(Conv2D(32, (5,5), activation='relu', input_shape=(128,128,3)))
model_I.add(MaxPooling2D(4, 4))

model_I.add(Conv2D(64, (3,3), activation='relu'))
model_I.add(MaxPooling2D(4, 4))

model_I.add(Conv2D(64, (3,3), activation='relu'))
model_I.add(MaxPooling2D(2, 2))

model_I.add(Flatten())
model_I.add(Dense(64, activation='relu'))
model_I.add(Dense(6, activation='softmax'))

# Model compilation
model_I.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy',
                       Precision(name='precision'),
                       Recall(name='recall'),
                       TopKCategoricalAccuracy(k=2, name='top2_acc')]
                )

# Loss and accuracy for test set before training
test_eval = model_I.evaluate(test_iterator, verbose=0)
print('Test loss:', test_eval[0])
print('Test accuracy:', test_eval[1])

# Loss and accuracy for validation set before training
val_eval = model_I.evaluate(val_iterator, verbose=0)
print('Initial validation loss:', val_eval[0])
print('Initial validation accuracy:', val_eval[1])

grad_monitor_I = GradientMonitor()
history_I = model_I.fit(train_iterator, epochs=10, validation_data=val_iterator, batch_size=128, callbacks=[grad_monitor_I])

evaluate_model(model_I)

plot_confusion_matrix(model_I, test_iterator)

generate_confusion_matrix_and_classification_report(model_I, test_iterator)

avg_grad_I = np.mean(grad_monitor_I.avg_gradients)
print("Average gradient norm for model_I:", avg_grad_I)

# Save model performance
save_model_performance(name="Simple neural network",
                       test_acc=test_acc,
                       test_loss=test_loss,
                       test_top_acc=test_top_acc,
                       avg_grad_norms=avg_grad_I,
                       train_params=train_params,
                       non_train_params=non_train_params,
                       model=model_I,
                       test_eval=test_eval,
                       grad_monitor=grad_monitor_I)



"""* Training Accuracy improved from 22.96% to 45.36%.
* Validation Accuracy improved from 25.3% to 45.73%.
* Both training and validation loss consistently decreased, indicating that the model is learning well without overfitting.
* Most correct predictions appear on the diagonal (e.g., 52 for paper, 45 for cardboard).
* Paper is often misclassified as metal (15 times) and plastic (35 times).
* Plastic also gets confused with glass (13 times).
* Metal is frequently misclassified as paper (13 times).
* There are no examples of trach class.

## Model 2 (dropout)
"""

model_II = Sequential()

model_II.add(Conv2D(32, (5,5), activation='relu', input_shape=(128,128,3)))
model_II.add(MaxPooling2D(4, 4))
model_II.add(Dropout(0.2))

model_II.add(Conv2D(64, (3,3), activation='relu'))
model_II.add(MaxPooling2D(4, 4))
model_II.add(Dropout(0.2))

model_II.add(Conv2D(64, (3,3), activation='relu'))
model_II.add(MaxPooling2D(2, 2))
model_II.add(Dropout(0.2))

model_II.add(Flatten())
model_II.add(Dense(64, activation='relu'))
model_II.add(Dense(6, activation='softmax'))

model_II.compile(optimizer='adam',
                 loss='categorical_crossentropy',
                 metrics=['accuracy',
                       Precision(name='precision'),
                       Recall(name='recall'),
                       TopKCategoricalAccuracy(k=2, name='top2_acc')]
                )

# Loss and accuracy for test set before training
test_eval = model_II.evaluate(test_iterator, verbose=0)
print('Test loss:', test_eval[0])
print('Test accuracy:', test_eval[1])

# Loss and accuracy for validation set before training
val_eval = model_II.evaluate(val_iterator, verbose=0)
print('Initial validation loss:', val_eval[0])
print('Initial validation accuracy:', val_eval[1])

grad_monitor_II = GradientMonitor()
history_II = model_II.fit(train_iterator, epochs=10, validation_data=val_iterator, batch_size=128, callbacks=[grad_monitor_II])

evaluate_model(model_II)

plot_confusion_matrix(model_II, test_iterator)

generate_confusion_matrix_and_classification_report(model_II, test_iterator)

avg_grad_II = np.mean(grad_monitor_II.avg_gradients)
print("Average gradient norm for model_II:", avg_grad_II)

# Save model performance
save_model_performance(name="Neural network with dropout",
                       test_acc=test_acc,
                       test_loss=test_loss,
                       test_top_acc=test_top_acc,
                       avg_grad_norms=avg_grad_II,
                       train_params=train_params,
                       non_train_params=non_train_params,
                       model=model_II,
                       test_eval=test_eval,
                       grad_monitor=grad_monitor_II)

"""* Training accuracy increased from 15.76% to 38.46%.

* Validation loss dropped from 1.7555 to 1.5205 (a reduction of 13.4%).

* Training and validation curves show steady learning with no major signs of overfitting.
* Glass class performance is weak: only 8/82 correctly predicted — accuracy ~9.75%.

* Trash class not detected at all: suggests feature overlap or lack of representation.

* Paper class is best-performing: 52/108 correct — accuracy ~48.15%.

* High confusion between paper, glass, plastic, and metal, which may share visual traits.

## Model 3 (normalization)
"""

# Updated Model
model_III= Sequential()

# Block 1
model_III.add(Conv2D(32, (3,3), padding='same', input_shape=(128,128,3)))
model_III.add(LayerNormalization())
model_III.add(Activation('relu'))
model_III.add(MaxPooling2D(2,2))

# Block 2
model_III.add(Conv2D(64, (3,3), padding='same'))
model_III.add(LayerNormalization())
model_III.add(Activation('relu'))
model_III.add(MaxPooling2D(2,2))

# Block 3
model_III.add(Conv2D(128, (3,3), padding='same'))
model_III.add(LayerNormalization())
model_III.add(Activation('relu'))
model_III.add(MaxPooling2D(2,2))
model_III.add(Dropout(0.25))

# Block 4
model_III.add(Conv2D(256, (3,3), padding='same'))
model_III.add(LayerNormalization())
model_III.add(Activation('relu'))
model_III.add(MaxPooling2D(2,2))
model_III.add(Dropout(0.35))

# Dense layers
model_III.add(Flatten())
model_III.add(Dense(256))
model_III.add(LayerNormalization())
model_III.add(Activation('relu'))
model_III.add(Dropout(0.5))

model_III.add(Dense(6, activation='softmax'))

model_III.compile(optimizer=Adam(learning_rate=1e-4),
                  loss='categorical_crossentropy',
                  metrics=['accuracy',
                       Precision(name='precision'),
                       Recall(name='recall'),
                       TopKCategoricalAccuracy(k=2, name='top2_acc')]
                )

# Loss and accuracy for test set before training
test_eval = model_III.evaluate(test_iterator, verbose=0)
print('Test loss:', test_eval[0])
print('Test accuracy:', test_eval[1])

# Loss and accuracy for validation set before training
val_eval = model_III.evaluate(val_iterator, verbose=0)
print('Initial validation loss:', val_eval[0])
print('Initial validation accuracy:', val_eval[1])

grad_monitor_III = GradientMonitor()
history_III = model_III.fit(train_iterator, epochs=10, validation_data=val_iterator, batch_size=128, callbacks=[grad_monitor_III])

evaluate_model(model_III)

plot_confusion_matrix(model_III, test_iterator)

generate_confusion_matrix_and_classification_report(model_III, test_iterator)

avg_grad_III = np.mean(grad_monitor_III.avg_gradients)
print("Average gradient norm for model_III:", avg_grad_III)

# Save model performance
save_model_performance(name="Neural network with normalization",
                       test_acc=test_acc,
                       test_loss=test_loss,
                       test_top_acc=test_top_acc,
                       avg_grad_norms=avg_grad_III,
                       train_params=train_params,
                       non_train_params=non_train_params,
                       model=model_III,
                       test_eval=test_eval,
                       grad_monitor=grad_monitor_III)

"""* Training accuracy improved significantly: +35.18 % (from 27.94% to 63.12%).

* Validation accuracy remained flat at 25.3% across all epochs.

* Model optimized well on training data, but failed to generalize to validation or test sets.
* Performance mirrors validation scores — indicating strong overfitting.

* Only one class ("paper") was predicted - severe model bias or data leakage.

## Model 4
"""

model_IV = Sequential()

model_IV.add(Conv2D(32, (5,5), kernel_regularizer=regularizers.L1L2(1e-5, 1e-4),
                    kernel_initializer='glorot_uniform', activation='relu', input_shape=(128,128,3)))
model_IV.add(MaxPooling2D(4, 4))
model_IV.add(LayerNormalization())
model_IV.add(Dropout(0.2))

model_IV.add(Conv2D(64, (3,3), kernel_regularizer=regularizers.L1L2(1e-5, 1e-4),
                    kernel_initializer='glorot_uniform', activation='relu'))
model_IV.add(MaxPooling2D(4, 4))
model_IV.add(LayerNormalization())
model_IV.add(Dropout(0.2))

model_IV.add(Conv2D(64, (3,3), kernel_regularizer=regularizers.L1L2(1e-5, 1e-4),
                    kernel_initializer='glorot_uniform', activation='relu'))
model_IV.add(MaxPooling2D(2, 2))
model_IV.add(LayerNormalization())
model_IV.add(Dropout(0.2))

model_IV.add(Flatten())
model_IV.add(Dense(128, activation='relu'))
model_IV.add(Dropout(0.2))
model_IV.add(Dense(6, activation='softmax'))

# Model compilation
model_IV.compile(optimizer='adam',
                 loss='categorical_crossentropy',
                 metrics=['accuracy',
                       Precision(name='precision'),
                       Recall(name='recall'),
                       TopKCategoricalAccuracy(k=2, name='top2_acc')]
                )

grad_monitor_IV = GradientMonitor()
history_IV = model_IV.fit(train_iterator, epochs=10, validation_data=val_iterator, batch_size=128, callbacks=[grad_monitor_IV ])

# Loss and accuracy for test set before training
test_eval = model_IV.evaluate(test_iterator, verbose=0)
print('Test loss:', test_eval[0])
print('Test accuracy:', test_eval[1])

# Loss and accuracy for validation set before training
val_eval = model_IV.evaluate(val_iterator, verbose=0)
print('Initial validation loss:', val_eval[0])
print('Initial validation accuracy:', val_eval[1])

evaluate_model(model_IV)

plot_confusion_matrix(model_IV, test_iterator)

generate_confusion_matrix_and_classification_report(model_IV, test_iterator)

avg_grad_IV = np.mean(grad_monitor_IV.avg_gradients)
print("Average gradient norm for model_IV:", avg_grad_IV)

# Save model performance
save_model_performance(name="Neural network with regularizers",
                       test_acc=test_acc,
                       test_loss=test_loss,
                       test_top_acc=test_top_acc,
                       avg_grad_norms=avg_grad_IV,
                       train_params=train_params,
                       non_train_params=non_train_params,
                       model=model_IV,
                       test_eval=test_eval,
                       grad_monitor=grad_monitor_IV)

"""* Training accuracy improved by 32.92 % (from 25.116% to 58.03%).

* Validation accuracy remained flat at 25.30% for all epochs.

* Loss reduction on training set shows learning — but no improvement on validation/test sets.
* Training-generalization gap persists - signs of severe overfitting.
* Only "paper" was predicted for all inputs — resulting in accuracy of 100% for paper and 0% for all other classes.

## Model 5 (MobileNet2)
"""

input_tensor = Input(shape=(128, 128, 3))
base_model = tf.keras.applications.MobileNetV2(
    include_top=False,
    input_tensor=input_tensor,
    weights='imagenet'
)
base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
output_tensor = Dense(6, activation='softmax')(x)

model_V = Model(inputs=base_model.input, outputs=output_tensor)

# Model compilation
model_V.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy',
                       Precision(name='precision'),
                       Recall(name='recall'),
                       TopKCategoricalAccuracy(k=2, name='top2_acc')]
                )

# Loss and accuracy for test set before training
test_eval = model_V.evaluate(test_iterator, verbose=0)
print('Test loss:', test_eval[0])
print('Test accuracy:', test_eval[1])

# Loss and accuracy for validation set before training
val_eval = model_V.evaluate(val_iterator, verbose=0)
print('Initial validation loss:', val_eval[0])
print('Initial validation accuracy:', val_eval[1])

grad_monitor_V = GradientMonitor()
history_V = model_V.fit(train_iterator, epochs=10, validation_data=val_iterator, batch_size=128, callbacks=[grad_monitor_V])

evaluate_model(model_V)

plot_confusion_matrix(model_V, test_iterator)

generate_confusion_matrix_and_classification_report(model_V, test_iterator)

avg_grad_V = np.mean(grad_monitor_V.avg_gradients)
print("Average gradient norm for model_V:", avg_grad_V)

# Save model performance
save_model_performance(name="MobileNet2",
                       test_acc=test_acc,
                       test_loss=test_loss,
                       test_top_acc=test_top_acc,
                       avg_grad_norms=avg_grad_V,
                       train_params=train_params,
                       non_train_params=non_train_params,
                       model=model_V,
                       test_eval=test_eval,
                       grad_monitor=grad_monitor_V)

"""* Validation accuracy improved by 24.08%.

* Validation loss decreased from 1.3351 to 0.6713.

* Indicates strong generalization and minimal overfitting.
* Test scores are in line with final validation scores — model shows excellent consistency.

# Model summary
"""

data = {
    "Model Name": model_name,
    "Test Accuracy": test_acc,
    "Test Loss": test_loss,
    "Test top 2 acc": test_top_acc,
    "Trainable Params": train_params,
    "Non-Trainable Params": non_train_params,
    "Avg gradient norms": [avg_grad_I, avg_grad_II, avg_grad_III, avg_grad_IV, avg_grad_V]
}

df = pd.DataFrame(data)
df

"""* **Baseline model**:  Decent test accuracy (42.92%) and loss (1.418), lowest parameters count (74,694) — lightweight and fast.
* **Neural netorok with dropout**: Slight drop in accuracy (37.8%) — possibly under-regularized, same parameters count, but dropout may have limited learning capacity.
* **Neural network with normalization**: Lowest test accuracy (25.06%) despite slightly more parameters, signs of prediction collapse (biased toward one class), some non-trainable params added via normalization layer.
* **Neural network with regularizers**:  Same test accuracy as previous model (25.06%) but highest parameter count (91,846), despite added complexity and regularization, shows overfitting and no gain.
* **MobileNetV2**: Best performer by far: 77.26% test accuracy, 0.6712 test loss, uses ~2.4M non-trainable parameters, balanced performance and generalization across all classes.

### Model MobileNet2 will be considered in the further analysis.
- Despite being pre-trained, MobileNetV2 adapted well — maintaining high accuracy across train, validation and test sets.

- Validation accuracy reached 76.52%, closely aligned with the test accuracy of 77.26%, indicating the model avoids overfitting and generalizes well.

- Thanks to its depthwise separable convolutions, MobileNetV2 extracts rich, hierarchical features without bloating the model size.
- Although the non-trainable parameters are large, the trainable part is lightweight — enabling fast and cost-efficient fine-tuning.
- Top performer in nearly every class, especially cardboard, paper, and glass. The remaining classes, especially trash, can benefit from targeted improvements.
"""